rem 共通メッセージ
set TDENC_NAME=TDEnc
set PROCESS_ANNOUNCE=処理中
set PAUSE_MESSAGE1=（TDEncを終了します、Enterキーを押してください）
set PAUSE_MESSAGE2=Enterキーを押してください。
set HORIZON=------------------------------------------------------------------------------
set HORIZON_B===============================================================================

rem 【ここに動画をD＆D】.batのメッセージ
set TDENC_TITLE=TDEnc
set PRESET_ALERT=プリセットのバージョンが古いです。
set USER_SETTING1=user_setting.batのバージョンが古いです。
set USER_SETTING2=user_setting.batを自動更新しますか？（y/n）
set PRESET_ALERT2=手動更新する場合はUSER_VERSIONの修正を行ってください。
set PRESET_ALERT3=（旧バージョンの設定は無視します）
set DOUBLECLICK_ALERT1=このファイルをダブルクリックしても、何も起こりません。
set DOUBLECLICK_ALERT2=動画ファイルをドラッグ・アンド・ドロップしてください。
set FILENAME_ERROR1=ファイル名の中に扱うことができない特殊な文字があります。
set FILENAME_ERROR2=List2で文字化けしているファイル名を変える必要があります。
set UNITE_AVI_ANNOUNCE1=分割AVI連結エンコード
set UNITE_AVI_ANNOUNCE2=※インタレ解除・フルレンジ機能などは無効
set ONE_MOVIE_ANNOUNCE=通常エンコードモード
set SEQUENCE_ANNOUNCE=連続エンコードモード
set MOVIE_INFO_ERROR1=動画解析に失敗しました。
set MOVIE_INFO_ERROR2=ユーザー名、フォルダ名、ファイル名に全角のスペースが使われてる可能性があります。
set MOVIE_INFO_ERROR3=　　対処法１：ファイル名から全角のスペースを削除する
set MOVIE_INFO_ERROR4=　　対処法２：一旦動画をドライブ（Cドライブ等）直下に移動する
set SEQUENCE_END1=完了しました。
set SEQUENCE_END2=出力先のファイルを確認後、このウィンドウを閉じてください。
set SEQUENCE_END3=
set MUX_ANNOUNCE=MUXエンコードモード
set MUX_ALERT1=.nvvファイルは対応していません
set MUX_ALERT2=DirectShow出力でAVIに書き出してから使ってください。
set SWF_ALERT=swfファイルはversion1.01からサポート対象外です。
set NVV_ALERT=nvvファイルはサポート対象外です。DirectShow出力プラグインでAVIにしてから使ってください。
set VIDEO_ENC_ERROR=映像のエンコードに失敗しました。
set AVS_MESSAGE1=Avisynthがインストールされていません。
set AVS_MESSAGE2=インストーラを起動します。この操作には管理者権限が必要です。
set AVS_MESSAGE3=「Japanese→同意する→次へ→インストール」の手順でインストールできます。

rem avs.bat、cat.bat、movie.bat、mux.bat、nvv.batのメッセージ
set ANALYZE_ANNOUNCE=動画解析中
set ANALYZE_END=動画解析完了
set ANALYZE_ERROR=動画の解析に失敗
set DECODE_ERROR1=動画のデコードに失敗
set DECODE_ERROR2=インデックス処理を再処理します。
set DECODE_ERROR3=正常にデコードできませんでした。
set VIDEO_ENC_ANNOUNCE=動画のエンコード処理に入ります。
set AVS_END=映像AVS作成完了
set VIDEO_ENC_END=動画エンコード完了
set SILENCE_ANNOUNCE=無音ファイルを作成
set AUDIO_ENC_ANNOUNCE=音声のエンコード処理に入ります。
set WAV_ANNOUNCE=WAVファイル作成中

rem create_mp4.batのメッセージ
set MP4_ANNOUNCE=MP4作成開始
set MP4_ERROR1=エンコードに失敗
set MP4_ERROR2=しました
set MP4_SUCCESS=MP4作成完了
set SIZE_SUCCESS1=動画ファイルの容量のチェック完了
set SIZE_SUCCESS2=容量制限クリア
set SIZE_ERROR=容量制限をオーバーしました
set DERE_MESSAGE1=完了
set DERE_MESSAGE2=しました。

rem initialize.batのメッセージ
set INIT_TITLE=初回起動時の設定
set INIT_ANNOUNCE=初回起動時の設定

rem m4a_enc.batのメッセージ
set SYNC_ANNOUNCE=音ズレ修正中
set WAV_END=WAVファイル作成完了
set M4A_ENC_ANNOUNCE=音声エンコ開始
set WAV_ERROR=音声が読み込めませんでした。無音ファイルを追加します。
set M4A_SUCCESS=音声エンコ完了しました。

rem setting_question.batのメッセージ
set QUESTION_START1=動画ファイルの要件を決定します。
set QUESTION_START2=次の質問に対して数字を入力して回答してください。
set LEVEL_START1=質問の詳しさを選択してください。（1～3）
set LEVEL_START2=（よく分からない場合は1を選んでください。）
set LEVEL_LIST1=すこし（初心者向け）
set LEVEL_LIST2=ふつう
set LEVEL_LIST3=おおめ（上級者向け）
set LEVEL_LIST4=※詳細な設定を行いたい場合は、user_setting.batを直接編集してください。
set UP_SITE_START1=アップロード先を選択してください。YouTube、ニコニコ動画、Twitter（y/n/N/t）
set UP_SITE_START2=（YouTubeならy、ニコニコならn(一部の新基準対象者はN)、Twitterならtを選びます。）
set PRESET_START1=プリセットを選択してください（l～x）
set PRESET_START2=（よく分からない場合はとりあえずmを選んでください）
set PRESET_LIST1=アニメーション等　速度重視（or 低スペックPC用）
set PRESET_LIST2=アニメーション等　バランス（エンコード速度・画質両立）
set PRESET_LIST3=アニメーション等　画質重視（or 高スペックPC用）
set PRESET_LIST4=実写等　速度重視（or 低スペックPC用）
set PRESET_LIST5=実写等　バランス（エンコード速度・画質両立）
set PRESET_LIST6=実写等　画質重視（or 高スペックPC用）
set PRESET_LIST7=音声エンコードのみ、高速
set PRESET_LIST8=ユーザー定義プリセット（デフォルトは時間がかかります）
set PRESET_LIST9=YouTube用（リサイズなし＆大容量でエンコード）
set PRESET_MESSAGE=プリセットsはmp4+wavでしか利用できません。
set RETURN_MESSAGE1=エラー　指定された中から文字を選択してください。
set PREMIUM_START1=プレミアムアカウントですか？（y/n）
set PREMIUM_START2=（一般アカウントの人はnを入力します）
set PREMIUM_START3=YouTubeのアップロード上限解除の設定はしていますか？（y/n）
set PREMIUM_START4=（アップロードできる動画の長さは、デフォルトでは 15 分までです。）
set PREMIUM_ERROR1=ニコニコのサーバ仕様変更で今までのエンコードはできなくなりました。
set PREMIUM_ERROR2=サイト選択のところで大文字のNを選択してください
set PREMIUM_ERROR3=（参照：https://tdenc.com/blog/2016/10/22/nico-new-format-3/）
set YOUTUBE_ERROR1=上限の解除をしていない場合は動画の長さは15分までです。
set YOUTUBE_ERROR2=動画を短く分割するか上限解除の設定をしてください。
set CHANNEL_ERROR1=ニコニコはステレオ（2ch）までしか対応していません。
set CHANNEL_ERROR2=音声のみwav（2ch）で書き出して動画と一緒にD＆Dしてください。
set CHANNEL_ERROR3=Twitterはステレオ（2ch）までしか対応していません。
set BR_MODE_START1=品質基準（crf）エンコードを有効にしますか？（y/n,CRF数値）
set BR_MODE_START2=※品質基準エンコードを使うことで適切なビットレートへの調整が可能
set BR_MODE_START3=　ビットレートがオーバーした場合は自動で無効に切り替わり、
set BR_MODE_START4=　ビットレート基準エンコードに自動で切り替わる
set BR_MODE_START5=（よくわからないならyを選んでください）
set ECONOMY_START1=エコ回避にエンコードしますか？高画質エンコードにしますか？（e/h）
set ECONOMY_START2=（よくわからないならhを選んでください）
set BITRATE_START1=目標ビットレート（音声＋映像）はいくつにしますか？（単位はkbps、入力例：1000）
set BITRATE_START2=（よく分からない場合は、0にすれば自動で設定します）
set RETURN_MESSAGE2=エラー　数字（だけ）を入力してください
set RETURN_MESSAGE3=エラー　ビットレートが高すぎます
set RETURN_MESSAGE4=きちんとビットレートの限界値より低く設定してください。
set DECODE_START1=再生負荷を軽くしますか？（y/n）
set DECODE_START2=（動画がカクつく時はyにすると少しだけだけ改善します）
set DECODE_START3=（高ビットレートや高解像度はyがお勧めです）
set DECODE_START4=（それ以外の場合にｙにすると画質が極端に落ちる場合あります）
set FLASH_START1=再生プレイヤーの仕様への対応について？（1～3）
set FLASH_START2=（映像が崩れる問題が出たときはこの数字を上げてみてください。
set FLASH_START3=　まずは1でテストして、実際の動画視聴で問題が出たら
set FLASH_START4=　2、3と変えてから処理し直してみることをおすすめします）
set FLASH_START5=　
set FLASH_LIST1=それなりに対応（今まで通り、ほとんどの場合これで十分）
set FLASH_LIST2=おおげさに対応（わりと過度な対応、画質を犠牲にする）
set FLASH_LIST3=完全互換が目標（画質をかなり犠牲にする、特にフェードや暗部）
set DEINT_START1=デインターレースしますか？（a/y/n）
set DEINT_START2=（aは必要かどうか自動判定、yは強制的にする、nは強制的にしない）
set DEINT_START3=（よく分からない場合はaを選んでください）
set RESIZE_START1=リサイズしますか？（入力例：y、n、768:432）
set RESIZE_START2=（yは自動、nはリサイズなし、:（半角）で区切って数値入力で直接指定）
set RESIZE_START3=※高解像度かつ高FPSの場合、動画視聴中にOSを巻き込んで落ちる場合があります。
set RESIZE_START4=　60fpsなどの時はリサイズすることをおすすめします。
set RESIZE_START5=（よくわからない場合はとりあえずyを選んでください）
set DENOISE_START1=デノイズしますか？（a/y/n）
set DENOISE_START2=（aは自動設定、yはデノイズあり、nはでノイズなし）
set DENOISE_START3=（よくわからない場合はとりあえずaを選んでください）
set AUDIO_START1=音声のビットレートはいくつにしますか？（入力例：160）
set AUDIO_START2=（画質重視：32～48、バランス：96～128、音質重視：192～224が目安です）
set AUDIO_START3=（無音でいいなら0を入力します）
set AUDIO_START4=※今回の動画で可能な音声ビットレートの限界値は
set AUDIO_START5=※今回の動画の総合（映像＋音声）ビットレートは
set RETURN_MESSAGE5=元のmp4の映像ビットレートが高すぎてmuxモードが使えません。
set RETURN_MESSAGE6=プリセットs以外を選んでください。
set SAMPLERATE_START1=音声のサンプルレートを選んでください（0～3）
set SAMPLERATE_START2=（よくわからない場合は1を選んでください）
set SAMPLERATE_LIST0=元の音声と同じ
set SYNC_START1=音ズレ処理をしますか？（入力例：y、n、-20、30）
set SYNC_START2=（yだとズレを差分から自動計算して音声の冒頭をカット。）
set SYNC_START3=（数値入力だと数値分だけ調整。負だとカット、正だと無音追加。単位はミリ秒）
set SYNC_START4=（よくわからない場合はとりあえずyを選んでください）
set RETURN_MESSAGE7=入力値のエラー
set RETURN_MESSAGE8=この映像ファイルは一般アカウントだとプリセットsは使えません
set RETURN_MESSAGE9=プレミアムアカウントになるか、プリセットs以外を使ってください
set RETURN_MESSAGE10=目標解像度が一般アカウントの制限を超えています。
set RETURN_MESSAGE11=プレミアムアカウントになるか、上限以下にリサイズをしてください。
set RETURN_MESSAGE12=目標解像度がTwitterの制限を超えています。
set RETURN_MESSAGE13=上限以下にリサイズをしてください。
set CONFIRM_START=最終確認
set CONFIRM_ON=有効
set CONFIRM_OFF=無効
set CONFIRM_PRETYPE=プリセット　　　
set CONFIRM_ACCOUNT1=投稿サイト　　　
set CONFIRM_ACCOUNT2=ニコニコ（プレミアム）
set CONFIRM_ACCOUNT3=ニコニコ（一般）
set CONFIRM_ACCOUNT4=YouTube（上限あり）
set CONFIRM_ACCOUNT5=YouTube（上限なし）
set CONFIRM_ACCOUNT6=ニコニコ（新基準）
set CONFIRM_ACCOUNT7=Twitter
set CONFIRM_PLAYER=プレイヤー対応　
set CONFIRM_ENCTYPE=エコ回避　　　　
set CONFIRM_DECTYPE=低再生負荷　　　
set CONFIRM_RESIZE1=リサイズ　　　　
set CONFIRM_RESIZE2=拡大
set CONFIRM_RESIZE3=縮小
set CONFIRM_VIDEO=映像　　　　　　
set CONFIRM_CRF=品質基準エンコ
set CONFIRM_BR=ビットレート基準エンコ
set CONFIRM_BITRATE1=目標ビットレート
set CONFIRM_DEINT1=デインターレース
set CONFIRM_DEINT2=自動判定（必要ならば解除）
set CONFIRM_DEINT3=強制有効
set CONFIRM_DEINT4=強制無効
set CONFIRM_DENOISE1=デノイズ　　　　
set CONFIRM_DENOISE2=自動設定
set CONFIRM_DENOISE3=あり
set CONFIRM_DENOISE4=なし
set CONFIRM_AUDIO=音声　　　　　　
set CONFIRM_NO_AUDIO=無音
set CONFIRM_SYNC1=音ズレ
set CONFIRM_SYNC2=自動調整
set CONFIRM_SYNC3=手動調整
set CONFIRM_T_BITRATE=総ビットレート　
set CONFIRM_T_CRF=自動調整（素材とアップロード先に合わせた適正値）
set CONFIRM_LAST1=これでよろしいですか？（y/n）
set CONFIRM_LAST2=エラーが発生しました。入力値に誤りがあります。

rem shut.batのメッセージ
set SHUT_TITLE=エンコードが完了しました。
set SHUT_ALERT=120秒後に全てのアプリケーションを終了後シャットダウンします。
set SHUT_CANCEL=（何かキーを押すとキャンセルします）
set CANCEL_MESSAGE=シャットダウンをキャンセルしました

rem tool_downloader.batのメッセージ
set DOWNLOADER_TITLE=ツールダウンローダー
set DOWNLOADER_ANNOUNCE=ツールをダウンロード・更新します
set DOWNLOADER_QUESTION1=すべてのツールを自動で落としますか？（y/n）
set DOWNLOADER_QUESTION2=（自分で手動で落としたい場合はnを入力）
set NERO_LICENSE1=neroAacEnc.exeを使用するにはライセンスに同意が必要です。
set NERO_LICENSE2=Nero AAC CodecのページをWEBブラウザで開くから「エンドユーザー使用許諾条項」を
set NERO_LICENSE3=しっかり読んだ後、このウィンドウに戻ってください
set NERO_QUESTION=Nero AAC Codecの「エンドユーザー使用許諾条項」に同意しますか？（y/n）
set DOWNLOADER_MANUAL=以下のサイトからひとつひとつ落として、Archivesフォルダに全部入れてください。
set DOWNLOADER_END=完了
set DOWNLOADER_ERROR1=以下のファイルのダウンロードに失敗しました
set DOWNLOADER_ERROR2=(理由：サーバ移転、ダウンローダ不具合、ネット切断、プロキシーの設定等)
set DOWNLOADER_ERROR3=インターネットに接続しているか確認して再度実行してください。
set DOWNLOADER_ERROR4=プロキシを利用している場合、別途設定が必要です。curlプロキシの利用.txtを参照。

rem tool_installer.batのメッセージ
set INSTALLER_TITLE=ツールインストーラー
set INSTALLER_ANNOUNCE=ツールをtoolフォルダに入れます。
set INSTALLER_END=完了

rem version_check.batのメッセージ
set VER_CHECK_ERROR=バージョンチェック失敗（回線切断orダウンローダ起動失敗orサーバダウン）
set VER_CHECK_NEW1=新しいバージョンが出ています。
set VER_CHECK_NEW2=（アップデートの方法はサイトの「つかいかた」をよんでください）
set VER_CHECK_LOG=更新内容
set UPDATE_QUESTION1=自動アップデートしますか？（y/n/s）
set UPDATE_QUESTION2=（このままエンコードを続けるならnを選択します）
set UPDATE_QUESTION3=（今後もこのバージョンをスキップし続けたいならsを選択します）
set UPDATE_ERROR=アップデート失敗（回線切断orダウンローダ起動失敗orサーバダウン）
set UPDATE_ANNOUNCE1=アップデート開始
set UPDATE_ANNOUNCE2=アップデート完了
set UPDATE_ANNOUNCE3=次に関連ツールのアップデートをしてから終了します。

rem x264_enc.batのメッセージ
set OPTION_SUCCESS=x264オプション設定完了
set X264_ENC_START=動画エンコ開始
set PASS_ERROR=パス数の設定が間違えています
set PASS_ANNOUNCE1=パス数自動設定モード
set PASS_ANNOUNCE2=１pass目
set PASS_ANNOUNCE3=２pass目
set PASS_ANNOUNCE4=容量が大きすぎます
set PASS_ANNOUNCE5=３passを実行します。
set PASS_ANNOUNCE6=３pass目
set PASS_ANNOUNCE7=強制1passモード
set PASS_ANNOUNCE8=強制2passモード
set PASS_ANNOUNCE9=強制3passモード
set PASS_ANNOUNCE10=CRFエンコ
